options:
  logging: CLOUD_LOGGING_ONLY

steps:
  # Install Node dependencies
  - name: node:18
    entrypoint: npm
    args: ["install"]

  # Run Prisma migration on Cloud SQL
  - name: node:18
    entrypoint: npx
    args: ["prisma", "migrate", "deploy"]
    env:
      - DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@35.244.8.252:5432/postgres?schema=public

  # Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA", "."]

  # Push the Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"]

  # Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--add-cloudsql-instances", "${_CLOUDSQL_CONNECTION}",
        "--set-env-vars", "DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@/postgres?host=/cloudsql/${_CLOUDSQL_CONNECTION}&schema=public",
        "--set-env-vars", "PORT=4000"
      ]

images:
  - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"
