steps:
  # 1. Install Node dependencies
  - name: node:18
    entrypoint: npm
    args: ["install"]
    id: install

  # 2. Run Prisma migration (With 60s timeout)
  - name: node:18
    entrypoint: sh
    args:
      - -c
      - |
        # Download Cloud SQL Proxy
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        
        # Start Proxy in background
        ./cloud_sql_proxy -instances=${_CLOUDSQL_CONNECTION}=tcp:5432 & sleep 5
        
        # Run migration
        npx prisma migrate deploy
    env:
      # LOOK HERE: Added "&connect_timeout=60" at the end
      - DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@127.0.0.1:5432/postgres?schema=public&connect_timeout=60

  # 3. Build the Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["build", "-t", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA", "."]

  # 4. Push the Docker image
  - name: gcr.io/cloud-builders/docker
    args: ["push", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"]

  # 5. Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      [
        "run", "deploy", "${_SERVICE_NAME}",
        "--image", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA",
        "--region", "${_REGION}",
        "--platform", "managed",
        "--allow-unauthenticated",
        "--add-cloudsql-instances", "${_CLOUDSQL_CONNECTION}",
        # Keep the socket connection for the live app
        "--set-env-vars", "DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@/postgres?host=/cloudsql/${_CLOUDSQL_CONNECTION}&schema=public",
        "--set-env-vars", "PORT=4000"
      ]

options:
  logging: CLOUD_LOGGING_ONLY