steps:
  # 0. Install dependencies
  - name: node:18
    entrypoint: npm
    args: ["install"]

  # 1. COMBINED STEP: Start Proxy, Wait, and Run Prisma Migrations 🚀
  - name: node:18  # Using node:18 as it has the environment needed for Prisma
    entrypoint: sh
    args:
      - -c
      - |
        # --- 1. PROXY SETUP (Node:18 image is usually based on Debian, so 'apt-get' may be needed for netcat)
        # Install tools: wget (for downloading), netcat (for the connection check)
        apt-get update && apt-get install -y wget netcat-openbsd

        # Download, chmod, and start the proxy in the background
        wget https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.11.0/cloud-sql-proxy.linux.amd64 -O cloud-sql-proxy
        chmod +x cloud-sql-proxy
        ./cloud-sql-proxy ${_CLOUDSQL_CONNECTION} --port=5432 &
        
        # --- 2. ROBUST WAIT CHECK
        echo "Waiting for Cloud SQL Proxy to start listening on 5432..."
        i=0
        while ! nc -z 127.0.0.1 5432; do
          if [ $i -ge 30 ]; then
            echo "Error: Cloud SQL Proxy failed to start within 30 seconds."
            exit 1
          fi
          sleep 1
          i=$((i+1))
        done
        echo "Cloud SQL Proxy is ready after $i seconds."

        # --- 3. RUN PRISMA MIGRATIONS (Proxy is now guaranteed to be running in the SAME container)
        npx prisma migrate deploy
        
    env:
      # This DATABASE_URL is essential for the build-time migration
      - DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@127.0.0.1:5432/postgres?schema=public&connect_timeout=60

  # 2. Build Docker image (Original Step 3 becomes Step 2)
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "build",
        "-t", "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA",
        "."
      ]

  # 3. Push Docker image (Original Step 4 becomes Step 3)
  - name: gcr.io/cloud-builders/docker
    args:
      [
        "push",
        "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"
      ]

  # 4. Deploy Cloud Run Service (Original Step 5 becomes Step 4)
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "${_SERVICE_NAME}"
      - "--image"
      - "${_REGION}-docker.pkg.dev/${_PROJECT_ID}/${_REPOSITORY}/${_SERVICE_NAME}:$SHORT_SHA"
      - "--region"
      - "${_REGION}"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--add-cloudsql-instances"
      - "${_CLOUDSQL_CONNECTION}"
      - "--set-env-vars"
      - "DATABASE_URL=postgresql://postgres:${_DB_PASSWORD}@localhost/postgres?host=/cloudsql/${_CLOUDSQL_CONNECTION}&schema=public"

options:
  logging: CLOUD_LOGGING_ONLY